# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\xa4\x01\n\x07Request\x12\r\n\x05Title\x18\x01 \x01(\t\x12\x13\n\x0b\x44istributor\x18\x02 \x01(\t\x12\x0e\n\x06\x42udget\x18\x03 \x01(\x05\x12\"\n\x1aOpeningWeekendNorthAmerica\x18\x04 \x01(\x05\x12\x14\n\x0cNorthAmerica\x18\x05 \x01(\x05\x12\x18\n\x10OtherTerritories\x18\x06 \x01(\x05\x12\x11\n\tWorldwide\x18\x07 \x01(\x05\"\x15\n\x05Reply\x12\x0c\n\x04text\x18\x01 \x01(\t21\n\x07Greeter\x12&\n\x06Notify\x12\x0e.greet.Request\x1a\x0c.greet.Replyb\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REPLY = DESCRIPTOR.message_types_by_name['Reply']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'greet_pb2'
  # @@protoc_insertion_point(class_scope:greet.Reply)
  })
_sym_db.RegisterMessage(Reply)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=23
  _REQUEST._serialized_end=187
  _REPLY._serialized_start=189
  _REPLY._serialized_end=210
  _GREETER._serialized_start=212
  _GREETER._serialized_end=261
# @@protoc_insertion_point(module_scope)
